


export const featureBasedLayerTypes = ["csv", "feature", "geojson"];

export const imageBasedLayerTypes = [
    "tile",
    "vector-tile",
    "imagery",
    "map-image",
    "wms",
    "wmts"
];

export const threeDLayerTypes = [
    "scene",
    "elevation",
    "point-cloud",
    "building-scene",
    "integrated-mesh",
    "dimension"
];

export const realTimeLayerTypes = [
    "stream"
];

export const routeLayerTypes = [
    "route"
];
export const layerGroups = ["MyLayers", "Basemap", 
    "Utilities",
    "AdministrativeBoundary",
    "NationalAddress",
    "AdministrativeRegions",
    "Building",
    "Elevation",
    "Geology",
    "GeographicalNames",
    "Government_Services",
    "Imagery",
    "LandCover",
    "LandParcels",
    "LandUse",
    "Nationaladdress",
    "PopulationDistribution",
    "TheSaudiArabiaNationalSpatialReferenceSystem",
    "Transport",
    "Water",
    "Projects"];
