import { InitialLayersConfiguration } from "@/interface";

export const baseMapLayerConfigurations: InitialLayersConfiguration[] = [
  //  {
  //   id: "Buildings",
  //   title: "Buildings",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Buildings/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Building"],
  //   visible: false,
  //   labelsEnabled: true,
  //   renderer: null,
  //   opacity: 1,
  //   labelingInfo: null,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "parcel",
  //   title: "Parcel",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Parcel/FeatureServer",
  //   portalItemId: null,
  //   groups: ["LandParcels"],
  //   visible: false,
  //   labelsEnabled: true,
  //   renderer: {
  //     type: "simple",
  //     symbol: {
  //       type: "simple-fill",
  //       outline: {
  //         color: [255, 255, 0, 1],
  //         width: 1,
  //       },
  //     },
  //   },
  //   opacity: 1,
  //   labelingInfo: [
  //     {
  //       labelExpressionInfo: { expression: "$feature.parcelnumber" },
  //       symbol: {
  //         type: "text",
  //         color: "yellow",
  //         haloColor: "black",
  //         haloSize: "1px",
  //         font: {
  //           size: 12,
  //           family: "Arial",
  //           weight: "bold",
  //         },
  //       },
  //       minScale: 5000,
  //       maxScale: 100,
  //     },
  //   ],
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "Basemap",
  //   title: "JDA Basemap",
  //   type: "VectorTileLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/BasemapClient/VectorTileServer?token=436QoMcmB8Aj4lPkZY4te-t8yaVgWHrK66DqOggHtWl4_uO5qMrJ8l_3m_IzkUzwh4hUe5fhdpvphxJoIxop_6mQHJZHOtNJXu9RFY5yLnpR2EgL4Cbb3dbAoG2x21fdJJT3tzbpJk4cbRGKAf3f5P1OqCy4LKoVDSpbghFYbWc.",
  //   portalItemId: null,
  //   groups: ["Basemap"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "Administrative_Regions",
  //   title: "Administrative Regions",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Administrative_Regions/MapServer",
  //   portalItemId: null,
  //   groups: ["AdministrativeRegions"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "Geological_Layers",
  //   title: "Geological Layers",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Geological_Layers/MapServer",
  //   portalItemId: null,
  //   groups: ["Geology"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "Governmental_Services",
  //   title: "Governmental Services",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Governmental_Services/MapServer",
  //   portalItemId: null,
  //   groups: ["Government_Services"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "Landuse",
  //   title: "Landuse",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Landuse/MapServer",
  //   portalItemId: null,
  //   groups: ["LandUse"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "Projects",
  //   title: "Projects",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Projects_geoportal/MapServer",
  //   portalItemId: null,
  //   groups: ["Projects"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "Transport",
  //   title: "Transport",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Transport/MapServer",
  //   portalItemId: null,
  //   groups: ["Projects"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "Atkins_Layers",
  //   title: "Atkins Basemap",
  //   type: "TileLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Atkins_Basemap_WTL1/MapServer",
  //   portalItemId: null,
  //   groups: ["AtkinsLayers"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },










  
   // {
  //   id: "jeddah-historical",
  //   title: "Jeddah Historical",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://services.arcgis.com/4TKcmj8FHh5Vtobt/arcgis/rest/services/JeddahHistorical/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Utilities"],
  //   visible: false,
  //   labelsEnabled: true,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "District",
  //   title: "District",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/District/MapServer",
  //   portalItemId: null,
  //   groups: ["Basemap"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "Lighting_Pole",
  //   title: "Lighting Pole",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Lighting_Pole/MapServer",
  //   portalItemId: null,
  //   groups: ["Basemap"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "POI_1",
  //   title: "POI 1",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/POI_1/MapServer",
  //   portalItemId: null,
  //   groups: ["Basemap"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "Projects",
  //   title: "Projects",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Projects/MapServer",
  //   portalItemId: null,
  //   groups: ["Basemap"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  //  {
  //   id: "SubMunicipality",
  //   title: "SubMunicipality",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/SubMunicipality/MapServer",
  //   portalItemId: null,
  //   groups: ["Basemap"],
  //   visible: false,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
 
];

export const sceneBasemapConfigurations: InitialLayersConfiguration[] = [
  // {
  //   id: "scene-buildings",
  //   title: "Buildings",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Buildings/FeatureServer",
  //   portalItemId: null,
  //   groups: ["LandParcels"],
  //   visible: false,
  //   labelsEnabled: true,
  //   labelingInfo: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  //   renderer: {
  //     type: "simple",
  //     symbol: {
  //       type: "polygon-3d",
  //       symbolLayers: [
  //         {
  //           type: "extrude",
  //           material: { color: [200, 200, 200, 0.8] },
  //           edges: {
  //             type: "solid",
  //             color: [50, 50, 50, 0.5],
  //           },
  //         },
  //       ],
  //     },
  //     label: "Buildings",
  //     visualVariables: [
  //       {
  //         type: "size",
  //         field: "height",
  //         valueUnit: "meters",
  //         valueExpression: "$feature.height",
  //       },
  //     ],
  //   },
  // },
  // {
  //   id: "scene-parcel",
  //   title: "Parcel",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Parcel/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Administrative Boundry", "Basemap"],
  //   visible: false,
  //   labelsEnabled: true,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
];
