import { InitialLayersConfiguration } from "@/interface";

export const baseMapLayerConfigurations: InitialLayersConfiguration[] = [
  {
    id: "layer1",
    title: "مناطق المملكة",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://services8.arcgis.com/G62CNq4aRFEDWLdk/arcgis/rest/services/%D9%85%D9%86%D8%A7%D8%B7%D9%82_%D8%A7%D9%84%D9%85%D9%85%D9%84%D9%83%D8%A9/FeatureServer",
    portalItemId: null,
    group: "AdministrativeRegions",
    visible: false,
    labelsEnabled: false,
    renderer: null,
    opacity: 1,
    labelingInfo: null,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "layer2",
    title: "Jeddah Historical",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://services.arcgis.com/4TKcmj8FHh5Vtobt/arcgis/rest/services/JeddahHistorical/FeatureServer",
    portalItemId: null,
    group: "Basemap",
    visible: false,
    labelsEnabled: false,
    renderer: null,
    opacity: 1,
    labelingInfo: null,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "layer3",
    title: "Jeddah Gates",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://services.arcgis.com/4TKcmj8FHh5Vtobt/arcgis/rest/services/JeddahGates/FeatureServer",
    portalItemId: null,
    group: "Basemap",
    visible: false,
    labelsEnabled: false,
    renderer: null,
    opacity: 1,
    labelingInfo: null,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "layer4",
    title: "Jeddah",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://services.arcgis.com/E9zsdsZPiSq52EFG/arcgis/rest/services/Jeddah/FeatureServer",
    portalItemId: null,
    group: "Basemap",
    visible: false,
    labelsEnabled: false,
    renderer: null,
    opacity: 1,
    labelingInfo: null,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "coffee-shops",
    title: "Coffee Shops",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://services3.arcgis.com/g9f7TnnmnQ9IOZWd/arcgis/rest/services/Jeddah_Sample/FeatureServer",
    portalItemId: null,
    group: "Basemap",
    visible: false,
    labelsEnabled: false,
    renderer: null,
    opacity: 1,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "jeddah-projects",
    title: "Jeddah Projects",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://services9.arcgis.com/ONBxkqBd9gmR0qpr/arcgis/rest/services/Jeddah_Projects_V1_0_WFL1/FeatureServer",
    portalItemId: null,
    group: "Projects",
    visible: false,
    labelsEnabled: false,
    renderer: null,
    opacity: 1,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "plan600",
    title: "Plan 600",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://services.arcgis.com/E9zsdsZPiSq52EFG/arcgis/rest/services/Jeddah_599_600/FeatureServer",
    portalItemId: null,
    group: "Basemap",
    visible: false,
    labelsEnabled: false,
    renderer: null,
    opacity: 1,
    minScale: 0,
    maxScale: 18,
  },
];

export const sceneBasemapConfigurations: InitialLayersConfiguration[] = [
  // {
  //   id: "scene-buildings",
  //   title: "Buildings",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Buildings/FeatureServer",
  //   portalItemId: null,
  //   group: ["LandParcels"],
  //   visible: false,
  //   labelsEnabled: true,
  //   labelingInfo: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  //   renderer: {
  //     type: "simple",
  //     symbol: {
  //       type: "polygon-3d",
  //       symbolLayers: [
  //         {
  //           type: "extrude",
  //           material: { color: [200, 200, 200, 0.8] },
  //           edges: {
  //             type: "solid",
  //             color: [50, 50, 50, 0.5],
  //           },
  //         },
  //       ],
  //     },
  //     label: "Buildings",
  //     visualVariables: [
  //       {
  //         type: "size",
  //         field: "height",
  //         valueUnit: "meters",
  //         valueExpression: "$feature.height",
  //       },
  //     ],
  //   },
  // },
  // {
  //   id: "scene-parcel",
  //   title: "Parcel",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Parcel/FeatureServer",
  //   portalItemId: null,
  //   group: ["Administrative Boundry", "Basemap"],
  //   visible: false,
  //   labelsEnabled: true,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
];
