import { InitialLayersConfiguration } from "@/interface";

export const baseMapLayerConfigurations: InitialLayersConfiguration[] = [
  // {
  //   id: "jeddah-historical",
  //   title: "Jeddah Historical",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://services.arcgis.com/4TKcmj8FHh5Vtobt/arcgis/rest/services/JeddahHistorical/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Utilities"],
  //   visible: true,
  //   labelsEnabled: true,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  {
    id: "Buildings",
    title: "Buildings",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Buildings/FeatureServer",
    portalItemId: null,
    groups: ["Building"],
    visible: false,
    labelsEnabled: true,
    renderer: null,
    opacity: 1,
    labelingInfo: null,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "District",
    title: "District",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/District/FeatureServer",
    portalItemId: null,
    groups: ["MyLayers"],
    visible: false,
    labelsEnabled: true,
    renderer: null,
    opacity: 1,
    labelingInfo: null,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "Garden",
    title: "Garden",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Garden/FeatureServer",
    portalItemId: null,
    groups: ["MyLayers"],
    visible: false,
    labelsEnabled: true,
    renderer: null,
    opacity: 1,
    labelingInfo: null,
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "parcel",
    title: "Parcel",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Parcel/FeatureServer",
    portalItemId: null,
    groups: ["MyLayers"],
    visible: false,
    labelsEnabled: true,
    renderer: {
      type: "simple",
      symbol: {
        type: "simple-fill",
        outline: {
          color: [255, 255, 0, 1],
          width: 1,
        },
      },
    },
    opacity: 1,
    labelingInfo: [
      {
        labelExpressionInfo: { expression: "$feature.parcelnumber" },
        symbol: {
          type: "text",
          color: "yellow",
          haloColor: "black",
          haloSize: "1px",
          font: {
            size: 12,
            family: "Arial",
            weight: "bold",
          },
        },
        minScale: 5000,
        maxScale: 100,
      },
    ],
    minScale: 0,
    maxScale: 18,
  },
  {
    id: "Basemap",
    title: "Basemap",
    type: "VectorTileLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/BasemapClient/VectorTileServer",
    portalItemId: null,
    groups: ["Basemap"],
    visible: false,
    labelsEnabled: false,
    labelingInfo: null,
    renderer: null,
    opacity: 1,
    minScale: 0,
    maxScale: 18,
  },
   {
    id: "SubDivision_Boundary",
    title: "SubDivision Boundary",
    type: "MapImageLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/SubDivision_Boundary/MapServer",
    portalItemId: null,
    groups: ["Basemap"],
    visible: false,
    labelsEnabled: false,
    labelingInfo: null,
    renderer: null,
    opacity: 1,
    minScale: 0,
    maxScale: 18,
  },
   {
    id: "SubMunicipality",
    title: "SubMunicipality",
    type: "MapImageLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/SubMunicipality/MapServer",
    portalItemId: null,
    groups: ["Basemap"],
    visible: false,
    labelsEnabled: false,
    labelingInfo: null,
    renderer: null,
    opacity: 1,
    minScale: 0,
    maxScale: 18,
  },
  // {
  //   id: "blocks",
  //   title: "Blocks",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BGT/BGT_objecttypen/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Administrative Boundry"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "buildings",
  //   title: "Buildings",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BGT/BGT_objecttypen/MapServer",
  //   portalItemId: null,
  //   groups: ["Basemap"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "roads",
  //   title: "Roads",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BAG/BAGv3/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Utilities", "Administrative Boundry"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "waterways",
  //   title: "Waterways",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BAG/BAGv3/MapServer",
  //   portalItemId: null,
  //   groups: ["Administrative Boundry"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "green-areas",
  //   title: "Green Areas",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BGT/BGT_standaard/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Utilities"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "urban-areas",
  //   title: "Urban Areas",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BGT/BGT_standaard/MapServer",
  //   portalItemId: null,
  //   groups: ["Administrative Boundry"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "mines",
  //   title: "Mines",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BAG/BAGv3/MapServer",
  //   portalItemId: null,
  //   groups: ["Administrative Boundry"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
  // {
  //   id: "roadblock",
  //   title: "Roadblock",
  //   type: "MapImageLayer",
  //   sourceType: "url",
  //   url: "https://basisregistraties.arcgisonline.nl/arcgis/rest/services/BGT/BGT_standaard/MapServer",
  //   portalItemId: null,
  //   groups: ["Utilities", "Basemap"],
  //   visible: true,
  //   labelsEnabled: false,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
];

export const sceneBasemapConfigurations: InitialLayersConfiguration[] = [
  {
    id: "scene-buildings",
    title: "Buildings",
    type: "FeatureLayer",
    sourceType: "url",
    url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Buildings/FeatureServer",
    portalItemId: null,
    groups: ["MyLayers"],
    visible: false,
    labelsEnabled: true,
    labelingInfo: null,
    opacity: 1,
    minScale: 0,
    maxScale: 18,
    renderer: {
      type: "simple",
      symbol: {
        type: "polygon-3d",
        symbolLayers: [
          {
            type: "extrude",
            material: { color: [200, 200, 200, 0.8] },
            edges: {
              type: "solid",
              color: [50, 50, 50, 0.5],
            },
          },
        ],
      },
      label: "Buildings",
      visualVariables: [
        {
          type: "size",
          field: "height",
          valueUnit: "meters",
          valueExpression: "$feature.height",
        },
      ],
    },
  },
  // {
  //   id: "scene-parcel",
  //   title: "Parcel",
  //   type: "FeatureLayer",
  //   sourceType: "url",
  //   url: "https://gis.jda.gov.sa/agserver/rest/services/Hosted/Parcel/FeatureServer",
  //   portalItemId: null,
  //   groups: ["Administrative Boundry", "Basemap"],
  //   visible: false,
  //   labelsEnabled: true,
  //   labelingInfo: null,
  //   renderer: null,
  //   opacity: 1,
  //   minScale: 0,
  //   maxScale: 18,
  // },
];
