trigger:
  - main

variables:
  - group: SDF-Secrets

jobs:
- job: dockerJdaJob
  displayName: 'Build on docker-jda'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals docker-jda
  steps:
    - script: |
        mkdir -p ~/.docker
        echo '{"registry-mirrors": ["https://hub-mirror.c.163.com"]}' > ~/.docker/config.json 
        
        # Create a .env file for docker-compose to use
        cat > .env << EOF
        NEXT_PUBLIC_ARCGIS_API_KEY=${NEXT_PUBLIC_ARCGIS_API_KEY}
        NEXT_PUBLIC_PORTAL_URL=${NEXT_PUBLIC_PORTAL_URL}
        NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL=${NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL}
        NEXT_PUBLIC_ADMIN_URL=${NEXT_PUBLIC_ADMIN_URL}
        NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
        NEXT_PUBLIC_AUTH_REFRESH_URL=${NEXT_PUBLIC_AUTH_REFRESH_URL}
        NEXT_PUBLIC_AUTH_LOGOUT_URL=${NEXT_PUBLIC_AUTH_LOGOUT_URL}
        NEXT_PUBLIC_PORTAL_USERNAME=${NEXT_PUBLIC_PORTAL_USERNAME}
        NEXT_PUBLIC_PORTAL_PASSWORD=${NEXT_PUBLIC_PORTAL_PASSWORD}
        NEXT_PUBLIC_TOKEN_SECRET=${NEXT_PUBLIC_TOKEN_SECRET}
        NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL_SDF_GEOAPP}
        NEXT_PUBLIC_MAPSERVICES_URL=${NEXT_PUBLIC_MAPSERVICES_URL}
        NEXT_PUBLIC_PORTAL_GROUP_NAME=${NEXT_PUBLIC_PORTAL_GROUP_NAME}
        NEXT_PUBLIC_JDA_EXTENT_URL=${NEXT_PUBLIC_JDA_EXTENT_URL}
        NEXT_PUBLIC_SDF_BASEMAP_URL=${NEXT_PUBLIC_SDF_BASEMAP_URL}
        NEXT_PUBLIC_CLOSEST_FACILITY_URL=${NEXT_PUBLIC_CLOSEST_FACILITY_URL}
        NEXT_PUBLIC_ROUTE_SERVICE_URL=${NEXT_PUBLIC_ROUTE_SERVICE_URL}
        NEXT_PUBLIC_EXPORT_GP_URL=${NEXT_PUBLIC_EXPORT_GP_URL}
        NEXT_PUBLIC_PRINT_GP_URL=${NEXT_PUBLIC_PRINT_GP_URL}
        NEXT_PUBLIC_UPLOAD_GP_URL=${NEXT_PUBLIC_UPLOAD_GP_URL}
        NEXT_PUBLIC_UPLOAD_URL=${NEXT_PUBLIC_UPLOAD_URL}
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}
        EOF
        
        # Use the .env file with docker-compose
        docker compose -f docker-compose.yml build
      displayName: 'Build Docker Image with Docker Mirror'
      env:
        NEXT_PUBLIC_ARCGIS_API_KEY: $(NEXT_PUBLIC_ARCGIS_API_KEY)
        NEXT_PUBLIC_PORTAL_URL: $(NEXT_PUBLIC_PORTAL_URL)
        NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL: $(NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL)
        NEXT_PUBLIC_ADMIN_URL: $(NEXT_PUBLIC_ADMIN_URL)
        NEXT_PUBLIC_AUTH_URL: $(NEXT_PUBLIC_AUTH_URL)
        NEXT_PUBLIC_AUTH_REFRESH_URL: $(NEXT_PUBLIC_AUTH_REFRESH_URL)
        NEXT_PUBLIC_AUTH_LOGOUT_URL: $(NEXT_PUBLIC_AUTH_LOGOUT_URL)
        NEXT_PUBLIC_PORTAL_USERNAME: $(NEXT_PUBLIC_PORTAL_USERNAME)
        NEXT_PUBLIC_PORTAL_PASSWORD: $(NEXT_PUBLIC_PORTAL_PASSWORD)
        NEXT_PUBLIC_TOKEN_SECRET: $(NEXT_PUBLIC_TOKEN_SECRET)
        NEXT_PUBLIC_APP_URL_SDF_GEOAPP: $(NEXT_PUBLIC_APP_URL_SDF_GEOAPP)
        NEXT_PUBLIC_MAPSERVICES_URL: $(NEXT_PUBLIC_MAPSERVICES_URL)
        NEXT_PUBLIC_PORTAL_GROUP_NAME: $(NEXT_PUBLIC_PORTAL_GROUP_NAME)
        NEXT_PUBLIC_JDA_EXTENT_URL: $(NEXT_PUBLIC_JDA_EXTENT_URL)
        NEXT_PUBLIC_SDF_BASEMAP_URL: $(NEXT_PUBLIC_SDF_BASEMAP_URL)
        NEXT_PUBLIC_CLOSEST_FACILITY_URL: $(NEXT_PUBLIC_CLOSEST_FACILITY_URL)
        NEXT_PUBLIC_ROUTE_SERVICE_URL: $(NEXT_PUBLIC_ROUTE_SERVICE_URL)
        NEXT_PUBLIC_EXPORT_GP_URL: $(NEXT_PUBLIC_EXPORT_GP_URL)
        NEXT_PUBLIC_PRINT_GP_URL: $(NEXT_PUBLIC_PRINT_GP_URL)
        NEXT_PUBLIC_UPLOAD_GP_URL: $(NEXT_PUBLIC_UPLOAD_GP_URL)
        NEXT_PUBLIC_UPLOAD_URL: $(NEXT_PUBLIC_UPLOAD_URL)
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: $(NEXT_SERVER_ACTIONS_ENCRYPTION_KEY)

    - script: |
        docker compose -f docker-compose.yml up -d
      displayName: 'Run Container'

- job: agent42Job
  displayName: 'Build on agent42'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals agent42
  steps:
    - script: |
        mkdir -p ~/.docker
        echo '{"registry-mirrors": ["https://hub-mirror.c.163.com"]}' > ~/.docker/config.json 
        
        # Create a .env file for docker-compose to use
        cat > .env << EOF
        NEXT_PUBLIC_ARCGIS_API_KEY=${NEXT_PUBLIC_ARCGIS_API_KEY}
        NEXT_PUBLIC_PORTAL_URL=${NEXT_PUBLIC_PORTAL_URL}
        NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL=${NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL}
        NEXT_PUBLIC_ADMIN_URL=${NEXT_PUBLIC_ADMIN_URL}
        NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
        NEXT_PUBLIC_AUTH_REFRESH_URL=${NEXT_PUBLIC_AUTH_REFRESH_URL}
        NEXT_PUBLIC_AUTH_LOGOUT_URL=${NEXT_PUBLIC_AUTH_LOGOUT_URL}
        NEXT_PUBLIC_PORTAL_USERNAME=${NEXT_PUBLIC_PORTAL_USERNAME}
        NEXT_PUBLIC_PORTAL_PASSWORD=${NEXT_PUBLIC_PORTAL_PASSWORD}
        NEXT_PUBLIC_TOKEN_SECRET=${NEXT_PUBLIC_TOKEN_SECRET}
        NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL_SDF_GEOAPP}
        NEXT_PUBLIC_MAPSERVICES_URL=${NEXT_PUBLIC_MAPSERVICES_URL}
        NEXT_PUBLIC_PORTAL_GROUP_NAME=${NEXT_PUBLIC_PORTAL_GROUP_NAME}
        NEXT_PUBLIC_JDA_EXTENT_URL=${NEXT_PUBLIC_JDA_EXTENT_URL}
        NEXT_PUBLIC_SDF_BASEMAP_URL=${NEXT_PUBLIC_SDF_BASEMAP_URL}
        NEXT_PUBLIC_CLOSEST_FACILITY_URL=${NEXT_PUBLIC_CLOSEST_FACILITY_URL}
        NEXT_PUBLIC_ROUTE_SERVICE_URL=${NEXT_PUBLIC_ROUTE_SERVICE_URL}
        NEXT_PUBLIC_EXPORT_GP_URL=${NEXT_PUBLIC_EXPORT_GP_URL}
        NEXT_PUBLIC_PRINT_GP_URL=${NEXT_PUBLIC_PRINT_GP_URL}
        NEXT_PUBLIC_UPLOAD_GP_URL=${NEXT_PUBLIC_UPLOAD_GP_URL}
        NEXT_PUBLIC_UPLOAD_URL=${NEXT_PUBLIC_UPLOAD_URL}
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}
        EOF
        
        # Use the .env file with docker-compose
        docker compose -f docker-compose.yml build
      displayName: 'Build Docker Image with Docker Mirror'
      env:
        NEXT_PUBLIC_ARCGIS_API_KEY: $(NEXT_PUBLIC_ARCGIS_API_KEY)
        NEXT_PUBLIC_PORTAL_URL: $(NEXT_PUBLIC_PORTAL_URL)
        NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL: $(NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL)
        NEXT_PUBLIC_ADMIN_URL: $(NEXT_PUBLIC_ADMIN_URL)
        NEXT_PUBLIC_AUTH_URL: $(NEXT_PUBLIC_AUTH_URL)
        NEXT_PUBLIC_AUTH_REFRESH_URL: $(NEXT_PUBLIC_AUTH_REFRESH_URL)
        NEXT_PUBLIC_AUTH_LOGOUT_URL: $(NEXT_PUBLIC_AUTH_LOGOUT_URL)
        NEXT_PUBLIC_PORTAL_USERNAME: $(NEXT_PUBLIC_PORTAL_USERNAME)
        NEXT_PUBLIC_PORTAL_PASSWORD: $(NEXT_PUBLIC_PORTAL_PASSWORD)
        NEXT_PUBLIC_TOKEN_SECRET: $(NEXT_PUBLIC_TOKEN_SECRET)
        NEXT_PUBLIC_APP_URL_SDF_GEOAPP: $(NEXT_PUBLIC_APP_URL_SDF_GEOAPP)
        NEXT_PUBLIC_MAPSERVICES_URL: $(NEXT_PUBLIC_MAPSERVICES_URL)
        NEXT_PUBLIC_PORTAL_GROUP_NAME: $(NEXT_PUBLIC_PORTAL_GROUP_NAME)
        NEXT_PUBLIC_JDA_EXTENT_URL: $(NEXT_PUBLIC_JDA_EXTENT_URL)
        NEXT_PUBLIC_SDF_BASEMAP_URL: $(NEXT_PUBLIC_SDF_BASEMAP_URL)
        NEXT_PUBLIC_CLOSEST_FACILITY_URL: $(NEXT_PUBLIC_CLOSEST_FACILITY_URL)
        NEXT_PUBLIC_ROUTE_SERVICE_URL: $(NEXT_PUBLIC_ROUTE_SERVICE_URL)
        NEXT_PUBLIC_EXPORT_GP_URL: $(NEXT_PUBLIC_EXPORT_GP_URL)
        NEXT_PUBLIC_PRINT_GP_URL: $(NEXT_PUBLIC_PRINT_GP_URL)
        NEXT_PUBLIC_UPLOAD_GP_URL: $(NEXT_PUBLIC_UPLOAD_GP_URL)
        NEXT_PUBLIC_UPLOAD_URL: $(NEXT_PUBLIC_UPLOAD_URL)
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: $(NEXT_SERVER_ACTIONS_ENCRYPTION_KEY)
