trigger:
  - main

variables:
  - group: SDF-Secrets

jobs:
- job: dockerJdaJob
  displayName: 'Build on docker-jda'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals docker-jda
  steps:
    - script: |
        mkdir -p ~/.docker
        echo '{"registry-mirrors": ["https://hub-mirror.c.163.com"]}' > ~/.docker/config.json 
        
        # Create a .env file for docker-compose to use with cache busting
        cat > .env << EOF
        CACHE_BUST=$(date +%s)
        NEXT_PUBLIC_ARCGIS_API_KEY=${NEXT_PUBLIC_ARCGIS_API_KEY}
        NEXT_PUBLIC_PORTAL_URL=${NEXT_PUBLIC_PORTAL_URL}
        PORTAL_TOKEN_SERVICE_URL=${PORTAL_TOKEN_SERVICE_URL}
        NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL=${NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL}
        NEXT_PUBLIC_ADMIN_URL=${NEXT_PUBLIC_ADMIN_URL}
        NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
        NEXT_PUBLIC_AUTH_REFRESH_URL=${NEXT_PUBLIC_AUTH_REFRESH_URL}
        NEXT_PUBLIC_AUTH_LOGOUT_URL=${NEXT_PUBLIC_AUTH_LOGOUT_URL}
        SDF_USERNAME=${SDF_USERNAME}
        SDF_PASSWORD=${SDF_PASSWORD}
        TOKEN_SECRET=${TOKEN_SECRET}
        NEXT_PUBLIC_APP_URL_SDF_GEOAPP=${NEXT_PUBLIC_APP_URL_SDF_GEOAPP}
        NEXT_PUBLIC_JDA_EXTENT_URL=${NEXT_PUBLIC_JDA_EXTENT_URL}
        NEXT_PUBLIC_SDF_BASEMAP_URL=${NEXT_PUBLIC_SDF_BASEMAP_URL}
        NEXT_PUBLIC_CLOSEST_FACILITY_URL=${NEXT_PUBLIC_CLOSEST_FACILITY_URL}
        NEXT_PUBLIC_ROUTE_SERVICE_URL=${NEXT_PUBLIC_ROUTE_SERVICE_URL}
        NEXT_PUBLIC_EXPORT_GP_URL=${NEXT_PUBLIC_EXPORT_GP_URL}
        NEXT_PUBLIC_PRINT_GP_URL=${NEXT_PUBLIC_PRINT_GP_URL}
        NEXT_PUBLIC_UPLOAD_GP_URL=${NEXT_PUBLIC_UPLOAD_GP_URL}
        NEXT_PUBLIC_UPLOAD_URL=${NEXT_PUBLIC_UPLOAD_URL}
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}
        EOF
        
        # Stop existing containers
        docker compose -f docker-compose.yml down || true
        
        # Force no-cache build to ensure fresh webpack chunks
        docker compose -f docker-compose.yml build --no-cache
      displayName: 'Build Docker Image with No Cache'
      env:
        NEXT_PUBLIC_ARCGIS_API_KEY: $(NEXT_PUBLIC_ARCGIS_API_KEY)
        NEXT_PUBLIC_PORTAL_URL: $(NEXT_PUBLIC_PORTAL_URL)
        PORTAL_TOKEN_SERVICE_URL: $(PORTAL_TOKEN_SERVICE_URL)
        NEXT_PUBLIC_ADMIN_URL: $(NEXT_PUBLIC_ADMIN_URL)
        NEXT_PUBLIC_AUTH_URL: $(NEXT_PUBLIC_AUTH_URL)
        NEXT_PUBLIC_AUTH_REFRESH_URL: $(NEXT_PUBLIC_AUTH_REFRESH_URL)
        NEXT_PUBLIC_AUTH_LOGOUT_URL: $(NEXT_PUBLIC_AUTH_LOGOUT_URL)
        SDF_USERNAME: $(SDF_USERNAME)
        SDF_PASSWORD: $(SDF_PASSWORD)
        TOKEN_SECRET: $(TOKEN_SECRET)
        NEXT_PUBLIC_APP_URL_SDF_GEOAPP: $(NEXT_PUBLIC_APP_URL_SDF_GEOAPP)
        NEXT_PUBLIC_JDA_EXTENT_URL: $(NEXT_PUBLIC_JDA_EXTENT_URL)
        NEXT_PUBLIC_SDF_BASEMAP_URL: $(NEXT_PUBLIC_SDF_BASEMAP_URL)
        NEXT_PUBLIC_CLOSEST_FACILITY_URL: $(NEXT_PUBLIC_CLOSEST_FACILITY_URL)
        NEXT_PUBLIC_ROUTE_SERVICE_URL: $(NEXT_PUBLIC_ROUTE_SERVICE_URL)
        NEXT_PUBLIC_EXPORT_GP_URL: $(NEXT_PUBLIC_EXPORT_GP_URL)
        NEXT_PUBLIC_PRINT_GP_URL: $(NEXT_PUBLIC_PRINT_GP_URL)
        NEXT_PUBLIC_UPLOAD_GP_URL: $(NEXT_PUBLIC_UPLOAD_GP_URL)
        NEXT_PUBLIC_UPLOAD_URL: $(NEXT_PUBLIC_UPLOAD_URL)
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: $(NEXT_SERVER_ACTIONS_ENCRYPTION_KEY)

    - script: |
        # Start the new containers with the fresh images
        docker compose -f docker-compose.yml up -d
        
        # Verify containers are running
        docker compose -f docker-compose.yml ps
      displayName: 'Deploy New Containers'

    - script: |
        # Clean up unused images to free space
        docker image prune -f
      displayName: 'Clean Up Old Images'

- job: agent42Job
  displayName: 'Build on agent42'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals agent42
  steps:
    - script: |
        mkdir -p ~/.docker
        echo '{"registry-mirrors": ["https://hub-mirror.c.163.com"]}' > ~/.docker/config.json 
        
        # Create a .env file for docker-compose to use with cache busting
        cat > .env << EOF
        CACHE_BUST=$(date +%s)
        NEXT_PUBLIC_ARCGIS_API_KEY=${NEXT_PUBLIC_ARCGIS_API_KEY}
        NEXT_PUBLIC_PORTAL_URL=${NEXT_PUBLIC_PORTAL_URL}
        PORTAL_TOKEN_SERVICE_URL=${PORTAL_TOKEN_SERVICE_URL}
        NEXT_PUBLIC_ADMIN_URL=${NEXT_PUBLIC_ADMIN_URL}
        NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
        NEXT_PUBLIC_AUTH_REFRESH_URL=${NEXT_PUBLIC_AUTH_REFRESH_URL}
        NEXT_PUBLIC_AUTH_LOGOUT_URL=${NEXT_PUBLIC_AUTH_LOGOUT_URL}
        SDF_USERNAME=${SDF_USERNAME}
        SDF_PASSWORD=${SDF_PASSWORD}
        TOKEN_SECRET=${TOKEN_SECRET}
        NEXT_PUBLIC_APP_URL_SDF_GEOAPP=${NEXT_PUBLIC_APP_URL_SDF_GEOAPP}
        NEXT_PUBLIC_JDA_EXTENT_URL=${NEXT_PUBLIC_JDA_EXTENT_URL}
        NEXT_PUBLIC_SDF_BASEMAP_URL=${NEXT_PUBLIC_SDF_BASEMAP_URL}
        NEXT_PUBLIC_CLOSEST_FACILITY_URL=${NEXT_PUBLIC_CLOSEST_FACILITY_URL}
        NEXT_PUBLIC_ROUTE_SERVICE_URL=${NEXT_PUBLIC_ROUTE_SERVICE_URL}
        NEXT_PUBLIC_EXPORT_GP_URL=${NEXT_PUBLIC_EXTRA_GP_URL}
        NEXT_PUBLIC_PRINT_GP_URL=${NEXT_PUBLIC_PRINT_GP_URL}
        NEXT_PUBLIC_UPLOAD_GP_URL=${NEXT_PUBLIC_UPLOAD_GP_URL}
        NEXT_PUBLIC_UPLOAD_URL=${NEXT_PUBLIC_UPLOAD_URL}
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}
        EOF
        
        # Stop existing containers
        docker compose -f docker-compose.yml down || true
        
        # Force no-cache build to ensure fresh webpack chunks
        docker compose -f docker-compose.yml build --no-cache
      displayName: 'Build Docker Image with No Cache'
      env:
        NEXT_PUBLIC_ARCGIS_API_KEY: $(NEXT_PUBLIC_ARCGIS_API_KEY)
        NEXT_PUBLIC_PORTAL_URL: $(NEXT_PUBLIC_PORTAL_URL)
        PORTAL_TOKEN_SERVICE_URL: $(PORTAL_TOKEN_SERVICE_URL)
        NEXT_PUBLIC_ADMIN_URL: $(NEXT_PUBLIC_ADMIN_URL)
        NEXT_PUBLIC_AUTH_URL: $(NEXT_PUBLIC_AUTH_URL)
        NEXT_PUBLIC_AUTH_REFRESH_URL: $(NEXT_PUBLIC_AUTH_REFRESH_URL)
        NEXT_PUBLIC_AUTH_LOGOUT_URL: $(NEXT_PUBLIC_AUTH_LOGOUT_URL)
        SDF_USERNAME: $(SDF_USERNAME)
        SDF_PASSWORD: $(SDF_PASSWORD)
        TOKEN_SECRET: $(TOKEN_SECRET)
        NEXT_PUBLIC_APP_URL_SDF_GEOAPP: $(NEXT_PUBLIC_APP_URL_SDF_GEOAPP)
        NEXT_PUBLIC_JDA_EXTENT_URL: $(NEXT_PUBLIC_JDA_EXTENT_URL)
        NEXT_PUBLIC_SDF_BASEMAP_URL: $(NEXT_PUBLIC_SDF_BASEMAP_URL)
        NEXT_PUBLIC_CLOSEST_FACILITY_URL: $(NEXT_PUBLIC_CLOSEST_FACILITY_URL)
        NEXT_PUBLIC_ROUTE_SERVICE_URL: $(NEXT_PUBLIC_ROUTE_SERVICE_URL)
        NEXT_PUBLIC_EXPORT_GP_URL: $(NEXT_PUBLIC_EXPORT_GP_URL)
        NEXT_PUBLIC_PRINT_GP_URL: $(NEXT_PUBLIC_PRINT_GP_URL)
        NEXT_PUBLIC_UPLOAD_GP_URL: $(NEXT_PUBLIC_UPLOAD_GP_URL)
        NEXT_PUBLIC_UPLOAD_URL: $(NEXT_PUBLIC_UPLOAD_URL)
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: $(NEXT_SERVER_ACTIONS_ENCRYPTION_KEY)

    - script: |
        # Start the new containers with the fresh images
        docker compose -f docker-compose.yml up -d
        
        # Verify containers are running
        docker compose -f docker-compose.yml ps
      displayName: 'Deploy New Containers'

    - script: |
        # Clean up unused images to free space
        docker image prune -f
      displayName: 'Clean Up Old Images'
