trigger:
  - main

pool:
  name: 'Default'

variables:
  imageName: 'geoportal'
  NEXT_PUBLIC_ArcGISAPIKey : 'AAPKc691d193fde14ea9bae49f48970f5fbcmPjkAffm__8tJdoM-iasTahd05z_ngTfiIdqY_FcU8Vp1t0my13dG7TlKBWfy5cx'
  NEXT_PUBLIC_PORTAL_URL : 'https://gis.jda.gov.sa/portal'
  NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL : 'https://gis.jda.gov.sa/portal/sharing/rest/generateToken'
  NEXT_PUBLIC_PORTAL_USERNAME : 'omaradmin'
  NEXT_PUBLIC_PORTAL_PASSWORD : '1qa2ws@WS!QA'
  TOKEN_SECRET : 'mySecureTokenSecret2030!@#$%^&*()_+=-[]{}|;:,.<>?'
  NEXT_PUBLIC_AUTH_URL: 'https://sdf.jda.gov.sa/auth'
  NEXT_PUBLIC_AUTH_REFRESH_URL: 'https://sdf.jda.gov.sa/auth/api/refresh-token'
  NEXT_PUBLIC_AUTH_LOGOUT_URL: 'https://sdf.jda.gov.sa/auth/api/logout'
  NEXT_PUBLIC_DB_USER: 'omer'
  NEXT_PUBLIC_DB_HOST: '192.168.1.20'
  NEXT_PUBLIC_DB_NAME: 'webdata'
  NEXT_PUBLIC_DB_PASSWORD: 'Om@123'
  PG_PORT: '5432'
  NEXT_PUBLIC_APP_URL : "https://sdf.jda.gov.sa"
      
steps:
  - script: |
      mkdir -p ~/.docker
      echo '{"registry-mirrors": ["https://hub-mirror.c.163.com"]}' > ~/.docker/config.json 
      
      # Create a .env file for docker-compose to use
      cat > .env << EOF
      NEXT_PUBLIC_ArcGISAPIKey=${NEXT_PUBLIC_ArcGISAPIKey}
      NEXT_PUBLIC_PORTAL_URL=${NEXT_PUBLIC_PORTAL_URL}
      NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL=${NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL}
      NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
      NEXT_PUBLIC_AUTH_REFRESH_URL=${NEXT_PUBLIC_AUTH_REFRESH_URL}
      NEXT_PUBLIC_AUTH_LOGOUT_URL=${NEXT_PUBLIC_AUTH_LOGOUT_URL}
      NEXT_PUBLIC_DB_USER=${NEXT_PUBLIC_DB_USER}
      NEXT_PUBLIC_DB_HOST=${NEXT_PUBLIC_DB_HOST}
      NEXT_PUBLIC_DB_NAME=${NEXT_PUBLIC_DB_NAME}
      NEXT_PUBLIC_DB_PASSWORD=${NEXT_PUBLIC_DB_PASSWORD}
      PG_PORT=${PG_PORT}
      NEXT_PUBLIC_PORTAL_USERNAME=${NEXT_PUBLIC_PORTAL_USERNAME}
      NEXT_PUBLIC_PORTAL_PASSWORD=${NEXT_PUBLIC_PORTAL_PASSWORD}
      TOKEN_SECRET=${TOKEN_SECRET}
      NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      EOF
      
      # Use the .env file with docker-compose
      docker compose -f docker-compose.yml build
    displayName: 'Build Docker Image with Docker Mirror'

  - script: |
      docker compose -f docker-compose.yml up -d
    displayName: 'Run Container'