FROM node:22-alpine

# Declare build arguments
ARG NEXT_PUBLIC_ARCGIS_API_KEY
ARG NEXT_PUBLIC_PORTAL_URL
ARG NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL
ARG NEXT_PUBLIC_AUTH_URL
ARG NEXT_PUBLIC_AUTH_REFRESH_URL
ARG NEXT_PUBLIC_AUTH_LOGOUT_URL
ARG NEXT_PUBLIC_PORTAL_USERNAME
ARG NEXT_PUBLIC_PORTAL_PASSWORD
ARG NEXT_PUBLIC_TOKEN_SECRET
ARG NEXT_PUBLIC_APP_URL_SDF_GEOAPP
ARG NEXT_PUBLIC_MAPSERVICES_URL
ARG NEXT_PUBLIC_PORTAL_GROUP_NAME
ARG NEXT_PUBLIC_JDA_EXTENT_URL
ARG NEXT_PUBLIC_SDF_BASEMAP_URL
ARG NEXT_PUBLIC_CLOSEST_FACILITY_URL
ARG NEXT_PUBLIC_ROUTE_SERVICE_URL
ARG NEXT_PUBLIC_EXPORT_GP_URL
ARG NEXT_PUBLIC_PRINT_GP_URL
ARG NEXT_PUBLIC_UPLOAD_GP_URL
ARG NEXT_PUBLIC_UPLOAD_URL
ARG NEXT_PUBLIC_ADMIN_URL
ARG NEXT_SERVER_ACTIONS_ENCRYPTION_KEY

# Set the working directory
WORKDIR /jda_geoportal

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

ENV NEXT_PUBLIC_ARCGIS_API_KEY=${NEXT_PUBLIC_ARCGIS_API_KEY}
ENV NEXT_PUBLIC_PORTAL_URL=${NEXT_PUBLIC_PORTAL_URL}
ENV NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL=${NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL}
ENV NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
ENV NEXT_PUBLIC_AUTH_REFRESH_URL=${NEXT_PUBLIC_AUTH_REFRESH_URL}
ENV NEXT_PUBLIC_AUTH_LOGOUT_URL=${NEXT_PUBLIC_AUTH_LOGOUT_URL}
ENV NEXT_PUBLIC_PORTAL_USERNAME=${NEXT_PUBLIC_PORTAL_USERNAME}
ENV NEXT_PUBLIC_PORTAL_PASSWORD=${NEXT_PUBLIC_PORTAL_PASSWORD}
ENV NEXT_PUBLIC_TOKEN_SECRET=${NEXT_PUBLIC_TOKEN_SECRET}
ENV NEXT_PUBLIC_APP_URL_SDF_GEOAPP=${NEXT_PUBLIC_APP_URL_SDF_GEOAPP}
ENV NEXT_PUBLIC_MAPSERVICES_URL=${NEXT_PUBLIC_MAPSERVICES_URL}
ENV NEXT_PUBLIC_PORTAL_GROUP_NAME=${NEXT_PUBLIC_PORTAL_GROUP_NAME}
ENV NEXT_PUBLIC_JDA_EXTENT_URL=${NEXT_PUBLIC_JDA_EXTENT_URL}
ENV NEXT_PUBLIC_SDF_BASEMAP_URL=${NEXT_PUBLIC_SDF_BASEMAP_URL}
ENV NEXT_PUBLIC_CLOSEST_FACILITY_URL=${NEXT_PUBLIC_CLOSEST_FACILITY_URL}
ENV NEXT_PUBLIC_ROUTE_SERVICE_URL=${NEXT_PUBLIC_ROUTE_SERVICE_URL}
ENV NEXT_PUBLIC_EXPORT_GP_URL=${NEXT_PUBLIC_EXPORT_GP_URL}
ENV NEXT_PUBLIC_PRINT_GP_URL=${NEXT_PUBLIC_PRINT_GP_URL}
ENV NEXT_PUBLIC_UPLOAD_GP_URL=${NEXT_PUBLIC_UPLOAD_GP_URL}
ENV NEXT_PUBLIC_UPLOAD_URL=${NEXT_PUBLIC_UPLOAD_URL}
ENV NEXT_PUBLIC_ADMIN_URL=${NEXT_PUBLIC_ADMIN_URL}
ENV NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}

# Build the Next.js application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
