FROM node:22-alpine

# Declare build arguments
ARG NEXT_PUBLIC_ArcGISAPIKey
ARG NEXT_PUBLIC_PORTAL_URL
ARG NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL
ARG NEXT_PUBLIC_AUTH_URL
ARG NEXT_PUBLIC_AUTH_REFRESH_URL
ARG NEXT_PUBLIC_AUTH_LOGOUT_URL
ARG NEXT_PUBLIC_DB_USER
ARG NEXT_PUBLIC_DB_HOST
ARG NEXT_PUBLIC_DB_NAME
ARG NEXT_PUBLIC_DB_PASSWORD
ARG PG_PORT
ARG NEXT_PUBLIC_PORTAL_USERNAME
ARG NEXT_PUBLIC_PORTAL_PASSWORD
ARG TOKEN_SECRET
ARG NEXT_PUBLIC_APP_URL

# Set the working directory
WORKDIR /jda_geoportal

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install --production
# RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables using build arguments
ENV NEXT_PUBLIC_ArcGISAPIKey=$NEXT_PUBLIC_ArcGISAPIKey
ENV NEXT_PUBLIC_PORTAL_URL=$NEXT_PUBLIC_PORTAL_URL
ENV NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL=$NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL
ENV NEXT_PUBLIC_AUTH_URL=$NEXT_PUBLIC_AUTH_URL
ENV NEXT_PUBLIC_AUTH_REFRESH_URL=$NEXT_PUBLIC_AUTH_REFRESH_URL
ENV NEXT_PUBLIC_AUTH_LOGOUT_URL=$NEXT_PUBLIC_AUTH_LOGOUT_URL
ENV NEXT_PUBLIC_DB_USER=$NEXT_PUBLIC_DB_USER
ENV NEXT_PUBLIC_DB_HOST=$NEXT_PUBLIC_DB_HOST
ENV NEXT_PUBLIC_DB_NAME=$NEXT_PUBLIC_DB_NAME
ENV NEXT_PUBLIC_DB_PASSWORD=$NEXT_PUBLIC_DB_PASSWORD
ENV PG_PORT=$PG_PORT
ENV NEXT_PUBLIC_PORTAL_USERNAME=$NEXT_PUBLIC_PORTAL_USERNAME
ENV NEXT_PUBLIC_PORTAL_PASSWORD=$NEXT_PUBLIC_PORTAL_PASSWORD
ENV TOKEN_SECRET=$TOKEN_SECRET
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

# Build the Next.js application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
# CMD ["npm", "run", "dev"]