FROM node:22-alpinARG NEXT_PUBLIC_PRINT_GP_URL
ARG NENV NEXT_PUBLIC_PRINT_GP_URL=$NEXT_PUBLIC_PRINT_GP_URL
ENV NEXT_PUBLIC_UPLOAD_GP_URL=$NEXT_PUBLIC_UPLOAD_GP_URL
ENV NEXT_PUBLIC_UPLOAD_URL=$NEXT_PUBLIC_UPLOAD_URLUBLIC_UPLOAD_GP_URL
ARG NEXT_PUBLIC_UPLOAD_URL# Declare build arguments
ARG NEXT_PUBLIC_ARCGIS_API_KEY
ARG NEXT_PUBLIC_PORTAL_URL
ARG NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL
ARG NEXT_PUBLIC_AUTH_URL
ARG NEXT_PUBLIC_AUTH_REFRESH_URL
ARG NEXT_PUBLIC_AUTH_LOGOUT_URL
ARG NEXT_PUBLIC_PORTAL_USERNAME
ARG NEXT_PUBLIC_PORTAL_PASSWORD
ARG TOKEN_SECRET
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_JDA_EXTENT_URL
ARG NEXT_PUBLIC_SDF_BASEMAP_URL
ARG NEXT_PUBLIC_CLOSEST_FACILITY_URL
ARG NEXT_PUBLIC_ROUTE_SERVICE_URL
ARG NEXT_PUBLIC_EXPORT_GP_URL
ARG NEXT_PUBLIC_PRINT_GP_URL
ARG NEXT_PUBLIC_UPLOAD_GP_URL
ARG NEXT_PUBLIC_UPLOAD_URL
ARG NEXT_PUBLIC_ADMIN_URL

# Set the working directory
WORKDIR /jda_geoportal

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install --production
# RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables using build arguments
ENV NEXT_PUBLIC_ARCGIS_API_KEY=$NEXT_PUBLIC_ARCGIS_API_KEY
ENV NEXT_PUBLIC_PORTAL_URL=$NEXT_PUBLIC_PORTAL_URL
ENV NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL=$NEXT_PUBLIC_PORTAL_TOKEN_SERVICE_URL
ENV NEXT_PUBLIC_AUTH_URL=$NEXT_PUBLIC_AUTH_URL
ENV NEXT_PUBLIC_AUTH_REFRESH_URL=$NEXT_PUBLIC_AUTH_REFRESH_URL
ENV NEXT_PUBLIC_AUTH_LOGOUT_URL=$NEXT_PUBLIC_AUTH_LOGOUT_URL
ENV NEXT_PUBLIC_PORTAL_USERNAME=$NEXT_PUBLIC_PORTAL_USERNAME
ENV NEXT_PUBLIC_PORTAL_PASSWORD=$NEXT_PUBLIC_PORTAL_PASSWORD
ENV TOKEN_SECRET=$TOKEN_SECRET
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_JDA_EXTENT_URL=$NEXT_PUBLIC_JDA_EXTENT_URL
ENV NEXT_PUBLIC_SDF_BASEMAP_URL=$NEXT_PUBLIC_SDF_BASEMAP_URL
ENV NEXT_PUBLIC_CLOSEST_FACILITY_URL=$NEXT_PUBLIC_CLOSEST_FACILITY_URL
ENV NEXT_PUBLIC_ROUTE_SERVICE_URL=$NEXT_PUBLIC_ROUTE_SERVICE_URL
ENV NEXT_PUBLIC_EXPORT_GP_URL=$NEXT_PUBLIC_EXPORT_GP_URL
ENV NEXT_PUBLIC_PRINT_GP_URL=$NEXT_PUBLIC_PRINT_GP_URL
ENV NEXT_PUBLIC_UPLOAD_GP_URL=$NEXT_PUBLIC_UPLOAD_GP_URL
ENV NEXT_PUBLIC_UPLOAD_URL=$NEXT_PUBLIC_UPLOAD_URL
ENV NEXT_PUBLIC_ADMIN_URL=$NEXT_PUBLIC_ADMIN_URL

# Build the Next.js application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
# CMD ["npm", "run", "dev"]